# Generated by Django 5.2.5 on 2025-09-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_user_alter_review_ratting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
