# Generated by Django 5.2.5 on 2025-09-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_review_rating_review_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='star',
            new_name='stars',
        ),
    ]
