# Generated by Django 5.2.5 on 2025-09-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_star_review_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='stars',
            new_name='rating',
        ),
    ]
